obs operator:
  obs type: WSpeed
obs space:
  source: truth
  obsdatain:
    obsfile: $(expdir)/{{current_cycle}}/obs.wspeed.{{current_cycle}}.nc
  obsdataout:
    obsfile: $(expdir)/{{current_cycle}}/obs.wspeed.$(experiment).{{current_cycle}}.nc
  obs type: WSpeed
obs error:
  covariance model: diagonal
